server:
  port: 9092
  servlet:
    session:
      timeout:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankcert?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      connection-timeout: 100000
      idle-timeout: 300000
      maximum-pool-size: 100
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/